---
name: github-actions-module-template # CHANGE THE NAME
description: Template file for using github actions for modules # CHANGE THE DESCRIPTION
branding:
  icon: 'chevron-right'
  color: 'blue'

runs:
  using: composite
  steps:
    # Change steps as needed here.
    # downloads terraform for use with listed pre-commit checks. Remove if not needed
    - name: Setup Terraform
      uses: TRI-IE/setup-terraform@v0.0.1
      with:
        terraform_wrapper: true
        
    # pre-commit checks are executed with this step
    - name: Run pre-commit checks
      uses: TRI-IE/pre-commit-checks@main
    
    