---
  name: main_update
  run-name: >-
    ${{ github.event.issue.number && format('module_update | PR-{0}', github.event.issue.number)
    || 'module template' }}
  
  permissions: read-all
  
  on:
    pull_request:
      types: [opened, synchronize]
      branches: main
  
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
  jobs:
    test-pipeline:
      runs-on: codebuild-<RUNNER_NAME>-${{ github.run_id }}-${{ github.run_attempt }}
      name: test-workflow
      permissions: write-all
  
  
      ############## Test your branch by pushing to the test branch of this repo ############################
      steps:
        - name: Run Composite Module
          uses: <ORG>/<REPO_NAME>@test
        